# Generated by Django 3.1.1 on 2021-02-08 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='works/static/img/')),
                ('titlle', models.CharField(max_length=100)),
                ('summary', models.TextField(max_length=200)),
                ('details', models.TextField()),
            ],
        ),
    ]
